plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

# Desabilitados — complexos ou que podem gerar bugs se autocorrigidos
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
